### ISSUE TITLE
[Socket] Support unix domain sockets

### ISSUE THREAD

**Issue by igorw** [reactphp/react#1]
By using the `unix://` stream wrapper with socket_server it should already be possible, but we need to expose this functionality somehow.

**Comment by nazar-pc** [comment]
Any updates?

**Comment by Orion1** [comment]
Aney updates?

**Comment by clue** [comment]
This is kind of an old issue and things have changed quite a bit since then :-)

React now consists of individual components that are maintained individually. Supporting Unix domain sockets is related to two components:

* https://github.com/reactphp/socket-client/issues/37
* https://github.com/reactphp/socket/issues/25

I suppose it makes sense to focus our related efforts on these issues.
