### ISSUE TITLE
PHP 5.5 generators

### ISSUE THREAD

**Issue by igorw** [reactphp/react#110]
It might be possible to do some sort of co-operative multitasking by using [generators](https://wiki.php.net/rfc/generators), which could potentially replace promises in the future.
- TaskJS: http://taskjs.org/
- em-synchrony: https://github.com/igrigorik/em-synchrony

Note: It has been done in python as well.

**Comment by clue** [comment]
This was already linked in the above discussion, but I'd to reiterate that [RecoilPHP](https://github.com/recoilphp/recoil) is probably the way to go if you want to use async coroutines with ReactPHP :tada: 

I believe this has been resolved, so I'm closing this for now. Please report back otherwise and we can reopen this :+1:
