### ISSUE TITLE
Interface or component for workers

### ISSUE THREAD

**Issue by igorw** [reactphp/react#13]
Sometimes apps will need synchronous I/O. This should not take place in the event loop, as it would block everything. Instead, it should be distributed to workers.

React should provide some way to interface with these workers (workers should use pre-forking). This could be a simple message queue abstraction interface or possibly a full-blown component that provides integration with redis, zeromq, maybe even rabbitmq (if somebody makes a non-blocking client lib).

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a long while and things have changed considerably since this ticket has been opened and it's unclear how much value this would provide nowadays. Please come back with more details if this is still an issue and we can reopen this :+1:

I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from our end (no demand at the moment and more important outstanding issues currently), but I suppose we would be really happy to accept PRs :+1:
