### ISSUE TITLE
Integrate mem leak tests in test suite

### ISSUE THREAD

**Issue by igorw** [reactphp/react#166]
The `examples/test-memory.php` file should be somehow integrated with the test suite and tested against all loops.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been resolved in the meantime. ReactPHP has evolved significantly since this ticket was opened, in particular the test suite has been improved to 100% coverage and a large number of projects have been using ReactPHP in production for years without any major issues. Please come back with more details if this problem persists and we can reopen this :+1:
