### ISSUE TITLE
[Socket] SSL support

### ISSUE THREAD

**Issue by igorw** [reactphp/react#2]
Possible by by using a stream context, see comment in: http://php.net/stream_socket_server

**Comment by cmstest** [comment]
Any news on this?

**Comment by tomhatzer** [comment]
Hi everybody!
Any news on this? :)
Thanks!
Tom

**Comment by clue** [comment]
Thanks for the elaborate discussion so far! :+1: 

This is kind of an old issue and things have changed quite a bit since then :-)

React now consists of individual components that are maintained individually. Supporting SSL/TLS is related to two components:

* [react/socket-client](https://github.com/reactphp/socket-client) - client-side sockets already support SSL/TLS
* [react/socket](https://github.com/reactphp/socket) - server-side sockets do not currently support SSL/TLS

As such, I've just filed a new ticket https://github.com/reactphp/socket/issues/24 to keep track of this, so I suppose it makes sense to focus our SSL/TLS related efforts on this component.
