### ISSUE TITLE
Warning on stream_select() when catching signal with pcntl_signal()

### ISSUE THREAD

**Issue by Divi** [reactphp/react#296]
Hello,

When catching a signal `SIGTERM` or `SIGINT` with the function `pcntl_signal()` there is a warning message just before the signal is catched :

    Warning: stream_select(): unable to select [4]: Interrupted system call (max_fd=17) in /vagrant/vendor/react/event-loop/StreamSelectLoop.php on line 252

or, on the second time with the same signal :

    Warning: stream_socket_accept(): accept failed: Interrupted system call in /vagrant/vendor/react/socket/Server.php on line 34

Tested with signal function :

    function () { die; }

**Comment by clue** [comment]
> Y'all have any progress for fix this bug?

Thanks for the discussion so far! :+1: 

This is kind of an old issue and things have changed quite a bit since then :-)

React now consists of individual components that are maintained individually. Supporting signal handling is now related to the [react/event-loop](https://github.com/reactphp/event-loop) component.

Somebody has already filed ticket https://github.com/reactphp/event-loop/issues/8 to keep track of this, so I suppose it makes sense to focus our signal handling related efforts on this component.
