### ISSUE TITLE
Is there a meaningful extension system in React? Is it at all documented?

### ISSUE THREAD

**Issue by cfv1984** [reactphp/react#321]
Hi everyone!
  I've been itching to contribute to React ever since I read about the project, but haven't been able to understand how to extend any of the several key points I could potentially want to use. Say, if I want to use `CFV\SpiffyNewResponse` instead of `React\Http\Response` (just an example) or maybe start building a MongoDB driver that plays nice into the general _way of working with react_ for one reason or another, there is just no clear guidance on how to do that, or even if such a thing is something that can be done. 

Hence my questions. Is this something that is already in place, or planned? Is there any documentation whatsoever on what the requirements to even start doodling such a thing are? How does one inject any non-default functionality at all into React?

**Comment by frodeborli** [comment]
I've wanted to do certain stuff to React as well, but since it is using "private" properties instead of "protected" properties most of the place it is kind of hard to add functionality without forking the entire project.

If properties had been protected, you could extend core classes and that way you would be able to inject functionality.

I have been working on an "application server" for react (https://github.com/frodeborli/fubber-reactor). It has a special controller type "ForkingController" that I am unable to get working without actually forking react core.

**Comment by assertchris** [comment]
Hey folks. The best way I've found, to hook into these private props is by [decoration](https://github.com/revolvephp/framework/blob/41aa337a84c26c494d8661c473fe0c5e0c483412/src/Http/Server.php#L10-L25)...

**Comment by cfv1984** [comment]
Unfortunately I don't really see how to apply that to cover my use case

**Comment by frodeborli** [comment]
I think you should patch react, by simply making the properties protected, instead of private. Send in a pull request on your change. You would then be able to override React\Http\Server and use your own version.

Also, React has a powerful event system. You can listen to events and hook into them. Take a look at the source code to find the events that are emitted. 

For the example you provide I would take the following approach:

    $loop = \React\EventLoop\Factory::create();
    $socket = new \React\Socket\Server($this->loop);
    $http = new \React\Http\Server($this->socket);
    $this->http->on('request', function($request, $response) {
       $myRequest = new PSRReactResponseWrapper($response);
       $myResponse = new PSRReactRequestWrapper($request);
    
       someRequestHandler($myRequest, $myResponse);
    });

I would look into https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md for my response/request wrappers.

**Comment by Beanow** [comment]
I'm running in the same issues, and the main reason seems to be not only the private properties but also extensive logic in the factories.

I'm using [AuraPHP](https://github.com/auraphp), which has a dependency injection system specifically designed for easily adding in your replacements (be it for mocking with tests or extending). But I constantly find myself negating the power of this system by using the various static `create` functions, which contain logic I otherwise can't access.

**Comment by clue** [comment]
For the most part, React uses interfaces and DI all over the place and allows you to inject custom instances and has an elaborate event mechanism that easily allows you to hook into.

Private properties came up multiple times already and we have yet to see some good arguments against them. Also, this is really a non-issue as it can easily be avoided by using the usually much cleaner decorator pattern as pointed out by @assertchris .

Let's make this actionable, what other issues are you seeing that need to be addressed? :+1:

**Comment by clue** [comment]
I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
