### ISSUE TITLE
ErrorException in callbacks

### ISSUE THREAD

**Issue by ortreum** [reactphp/react#376]
Hi,

maybe I don't understand the concept of reactPHP not well enough. But if I use the functions

    error_reporting(0);
    set_error_handler([$this, 'handle'], E_ALL);
    set_exception_handler([$this, 'exception']);
    register_shutdown_function([$this, 'shutdown']);

I thought that they will work inside the callback too. Every typo returns a HTTP 500 in the exmple react/http. It would be much more easier if there would be an ErrorException for E_ERROR, E_WARNING ect. like

    function handle($code, $text, $file, $line)
    {
         throw new \ErrorException($text, $code, 1, $file, $line);
     }

Or how can I do that myself?

Michael

**Comment by clue** [comment]
It looks like you're referring to react/http here? I think it makes sense for the server to catch any errors that occur during execution of the request handler, as the whole server would otherwise quit.

This example from the README shows how an `error` event can be processed in your code:

```php
$server->on('error', function (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```

See https://github.com/reactphp/http#server and also https://github.com/reactphp/http/pull/155 for an outstanding PR to properly report `Throwable` objects to the `error` handler.

I hope this helps :+1:

**Comment by ortreum** [comment]
Hi Christian,

thank you for your kind answer.
But your example only shows how to handle exceptions but not fatals, errors and warning. Nor I am not be able to bind an errorhandler to an function that throws an exception that I can handle like in the readme example.
I moved my issue to https://github.com/reactphp/http/issues/204

Michael
