### ISSUE TITLE
Use without composer

### ISSUE THREAD

**Issue by mlhkr** [reactphp/react#402]
Hi,
I'm using PHP 7.2.3 x64 on Windows 10 (IIS 10).
Since I can't install composer on windows (installer or manual install not working).
Tried it for couple of days without luck.
Any chance I can use it without composer?

Thanks

**Comment by clue** [comment]
This project highly recommends using Composer dependencies because it's the only sane way to manage our dependencies. That being said, it doesn't strictly *require* Composer for installation (neither do most other PHP projects). Manual installation requires some (significant) effort and is not really related to this project at all. I would suggest using some platform like Stackoverflow to figure out what's going on with your installation issues or asking for possible alternatives there.

I hope this helps :+1:

**Comment by mlhkr** [comment]
Solved:
+ Install ubuntu on virtual machine
+ Install php 7.2 with dependencies
+ Install composer
+ Install react (full) with composer
+ zip the whole vendor directory
+ copy to development windows machine and extract it
+ simple include_once "vendor/autoload.php"; vill solve everything then

but again, there should be a simple solution...

**Comment by clue** [comment]
Happy to hear you've got this solved one way or another! :+1: 

There are a number of solutions to this particular problem – neither of which is related to this project. I'd say this is a decent approach if it works for your use case :+1:
