### ISSUE TITLE
Debugging project with phpstorm and xdebug

### ISSUE THREAD

**Issue by horror** [reactphp/react#420]
Hi. I try use debugger with ide phpstorm, but I can't get it to work. Debagger will not stop on breakpoint, because React php works in multiple instances and async. Are there any synchronous modes or methods for comfortable development with xdebug?

**Comment by clue** [comment]
@horror Welcome to @ReactPHP! :tada: 

Using a debugger with ReactPHP to step through your code is certainly more *involved* due to its async nature, but other than that it should work just like any traditional CLI application. As such, I would suggest making sure Xdebug works in a simple command line script and then it should also work with ReactPHP.

I hope this helps! I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:

**Comment by neokree** [comment]
You can find a tutorial for debugging reactPHP apps here: https://medium.com/@neokree/debugging-a-reactphp-application-57a33e66b56d
