### ISSUE TITLE
Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead

### ISSUE THREAD

**Issue by michealzh** [reactphp/react#424]
The react package is required in davegardnerisme/nsqphp, after using `composer update` command,there is a message show in blew:
```
Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.
```
I wander how to avoid to hide warning message.

**Comment by WyriHaximus** [comment]
By updating `davegardnerisme/nsqphp` to use `react/socket` instead of `react/socket-client`. We're continuously updating our packages and we merged `react/socket-client` into `react/socket` about two years ago. That also means you're two years behind on new features and bug fixes. We also reccomend using our components directly instead of using the meta package.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by michealzh** [comment]
> By updating `davegardnerisme/nsqphp` to use `react/socket` instead of `react/socket-client`. We're continuously updating our packages and we merged `react/socket-client` into `react/socket` about two years ago. That also means you're two years behind on new features and bug fixes. We also reccomend using our components directly instead of using the meta package.

Thank you for your reply.
